#! /bin/bash
python train.py -d 0 -s 1 -e 6 -i 5
python predict.py -d 0 -s 1 -e 6
python evaluate.py -s 1 -e 6

python train.py -d 0 -s 1 -e 22
python predict.py -d 0 -s 1 -e 22
python evaluate.py -s 1 -e 22

python train.py -d 0 -s 1 -e 1
python predict.py -d 0 -s 1 -e 1
python evaluate.py -s 1 -e 1

python train.py -d 0 -s 1 -e 3
python predict.py -d 0 -s 1 -e 3
python evaluate.py -s 1 -e 3

python train.py -d 0 -s 1 -e 7
python predict.py -d 0 -s 1 -e 7
python evaluate.py -s 1 -e 7

python train.py -d 0 -s 1 -e 8
python predict.py -d 0 -s 1 -e 8
python evaluate.py -s 1 -e 8

python train.py -d 0 -s 1 -e 13
python predict.py -d 0 -s 1 -e 13
python evaluate.py -s 1 -e 13